baseURL = "https://benjaminkoltermann.me"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"
enableEmoji = true

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

#TODO Footer blogs rein

  [[menu.header]]
  name = "Tech Blog"
  URL = "https://p4ck3t0.de"
  weight = 2

  [[menu.header]]
  name = "Kubernetes Blog"
  URL = "https://kubernetes-security.com"
  weight = 3

  [[menu.header]]
  name = "Current Projects"
  URL = "#portfolio"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 5

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Experience"
  URL = "#experience"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 5


[params]

  # sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]
  sections = ["showcase", "about", "education", "testimonial", "experience", "client-and-work", "contact"]

  homepageExperienceCount = 6

  [params.google_analytics]
      code = ""
      enabled = false
  [params.google_tag_manager]
      code = ""
      enabled = false

  [params.logo]
    text1 = "Benjamin"
    text2 = "Koltermann"

  [params.footer]
      copyright = "© Benjamin Koltermann"
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
